authors:
  navin:
    name: Navin Kumar Balagopal
    description: Scientist, Artist & InBetween
    avatar: https://secure.gravatar.com/avatar/be89dae57f035101d38f6cf05428fe70a5f25f4bbd4f5805ad67125f912b8bd2?s=200&d=mm&r=g
    url: https://navinvent.com/
